#sudo is required for using docker
sudo: required
services:
  - docker
# what to run before installing
before_install:
  - docker build -t ozkhan/reading_client -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ozkhan/reading_client npm run test
deploy:
  provider: heroku
  api_key:
    secure: "F3coS2CRuLpGuJxd3D46rsIFYpCdwrxdIMVodWGIcJf1MDEqPGnNiPWX7/LiH5ZuFdExzkj/WSW5Riyd1cMV2KpGGjhx5ieLF0C4GP+aLDtpWJvro/WtjPzK1FVPAlK6m6nQSLVWVvFPrqGFTBm6WkpoPq9kQzfC/oWHwviJ3LCNkDLPb9qNPxie2Tth/FrLLwPktMKgOloQaMpuuLwb5s/QC7cBYh2txRokmy8+sITjbtvmOqyEKHpEur6lpMb8yV8mhHOb8ruvdgTH/hr7WZevkWNehSD92cxZiqZez4gBCV3kS/ioa2Z6x0nFMt7sKlHz9bMdPzSK9DNgXK2AXYcOEeL9gOVgw8z5GifCK9rU4aEfyfgc3b4njKgT8wpbGafZNXbks1hIS9x9ZBAG1A4VaVCpN2X0yO0aqF2P5RjGshe/BQbS96+ZI0VR1p3QcMljTULXItBgYUzbH+usx00UvMk+AtPt6R65SFSoWM63pZjBj8qF4oTYOpDaMnev5pG5DlP+xlj28/UJgn+w1hCOeG4AGgGrr87bUT4RPulh+X/9/wxbsab1lCoPr4SWDj+ZVOiK3tCpsGru9NqOBRGRCoLEFqQ1KPgnIelR1QtOqPr7S1xRyiJ8aImE8GAlLFNHsVUOzjmuvNrl4ox3WjgqBeWPG2UJrdebTXyC7CM="
  app: stark-dusk-07467
  on:
    repo: QueensCoder/reading-list
