#sudo is required for using docker
sudo: required
services:
  - docker
# what to run before installing
before_install:
  - docker build -t ozkhan/docker_react -f Dockerfile.dev .
script:
  - docker run -e CI=true ozkhan/docker_react npm run test

deploy:
  provider: heroku
  api_key:
    secure: "mYPL6m+wrqbhx+v9Ew7YDvCYt2O45GP5QpqgtlhpVKGHj3iSF2mN8D6ZuWx5+Nd+LroosW9yeTtzNnxNIa7hfekfyvqFF3G7RXVBv84dy7cmaGTlpZqNuG/MqR/ODEC5tSfQRB1fraPQhN4oZP+6r/ZWGFtOf9NIsvCtTOnLgvAoTeBvHYI1QpVsISO2vGqxjIvNpSCOFahMdZRiTFxmMwtZKbH7b9QJ6gzZRGVbPZROyY9zNsECMZZJ93KrBrw1j1t7NQs01JOv8TW0P3pLHH31NtF7JfStZEFPz/+VCCGDVvfNesE4VTbbdZJylxK2wpthntfE0y18OmCo6gtH6Y9ZlNl9GgWmGwtvj+3WmYO7hlRtGy0VrgD7wDx4DnJPMpEnTUfuxVIMLKQ0LBbedrBFaly4Ttm2JOXOCFZOIpiMEMgkpqkhtY+9C/B2bzn0HQZ3exoqlGddvEGSTrUOXpr3NIGksTzh2voiy1eM2jZEmVwibWFMOHIJpSLuEBjx8iI6zUanFMep8WjRBeRvi3bwypl2pbWPkG1+HhiHs0i9EKwDuttrcOTmuDhvIcm5eRnlSsVs8/UisXunBFR9aZYKIrZXcLfN5OtsfGgtEFZH1kxUbzVuQeLHD2wkWf5vAwMoKyHSr6SxkUEUA0gEI3mxfiO6xYSnSys9BlevfF8="
  app: reading-list-hooks
  on:
    repo: QueensCoder/reading-list
