#sudo is required for using docker
sudo: required
services:
  - docker
# what to run before installing
before_install:
  - docker build -t ozkhan/docker_react -f Dockerfile.dev .
script:
  - docker run -e CI=true ozkhan/docker_react npm run test

deploy:
  provider: heroku
  api_key:
    secure: "MyWj9PUgjqFdvahcOB1XJFfeLYjAeNmsw92Zdsbu3wlSjhIX4TosG5S8r7q5jrn8Oq7SWH8AYfXYsMdS74uPPW31fuTZd57JQ8I2C5BBK7/N9RqXw1P25tXt3RAUjBm7w66gDKkVUf+hR23IU08LWqyMOaZ3QUDXIoEZ92+XXtycKwmC7eT0D4KIrUNib/29QfE3689HbUayNaSk2hoYP83WWaTLpwe7a/nBdOlQsTFJ/Vfke6gmnt1X09gkC1k4p5YeApMOahQfI8Vncs7SL2qLlkHw3XdO65Yo+TIqUOabC3UsLS3+mqdRchgTUnZTlwk8hCW2O9minx19dlH/mDDemvil+eatUw8JkCx8Xc6fT9VvQQA4OL56tQM0tx+Q9RRmtSYnjlj8hCQxCMqOscfZxU8mZwJw3K04hYhZEL+ixG2mulPqWFM3PahtZIZRtimbC6ec/IP1468ioOJ58x7YyHVLDXc1Ls2ZP+RLzuIkob4FeK9MIt++a9stggl3kbZdQXJJFERpdWfeU4at8YabxytDWHrhQ9oRUHKw687DvorfbjBIYGf9GZRu4f4lktBl2NXUBk0spT/M496T8rmgqqm7+6VqBxvZaiXFzv8wRrrGcYRCN23alM4LU7Di++cTSpOLZz2e9MupYGaP8wvKH1cmanq650xzbhATASw="
  app: reading_list
  on:
    repo: QueensCoder/reading-list
