#sudo is required for using docker
sudo: required
services:
  - docker
# what to run before installing
before_install:
  - docker build -t ozkhan/docker_react -f Dockerfile.dev .
script:
  - docker run -e CI=true ozkhan/docker_react npm run test
deploy:
  provider: heroku
  api_key:
    secure: "Jb6jgs0ZSCG9hER3QX8RcmkbSotOfQMLEQAT9koI/kNOWMJ+xo8fFICXr5j3I+hfuJxUPm0EJtbNpa2FKgkU1MG6x1y6ggFOrd6extNPiMOghjoAlspcX/KKY3gwrZUkM2DV1g28ANZa1J5gYSZSA1U22vFx/vEf7D01ka3jyOxI1SXOKRpLPatjXoNd2Di7WyOSLhfz9UciHmUcLS6krWl++XDivSgki40Lu7ZXdwcgZJoce8tGPru3cp0AZDZ1OMjScmwllbenudaglVceFjg+2cxz0dsekXk+i70anzD9AJ2KnbHbHhBwe4UJ9lbL98pZ9MiZDULaGA5ywGly+G4T3hFSJMfhftALGxHjXwePoEo6jjzhwZ0i5S4fPZL4Phj4S3ZelUERgKPaEdtRUOYLtjZ4vtFGhel9QR5sBjaG1x3rzZOzbGj4941syJzp/NHJ208YeWC7WoE9CqfNGsSmUc0R//gVK4m1D5RtJJT5tHixFLUrRlLXsbEA81s+etqISw+3lHMc6uLGbaKPGYV3/lSdjsfaoGIfLmOzbsnkp5HlSgKXn+BffkrajJkAQeUScuXgUhrsa4kDg5T28NTdFDkDefW6djniYauMK9hTrFy+r6tbxKcuUco91DMJIccrgiW66Ykq7Be//IzVT44RefABIlIYnDhyi8XS17g="
  app: stark-dusk-07467
  on:
    repo: QueensCoder/reading-list
