version: "3"
services:
  web:
    build:
      # in the event that there is no docker file look in curr dir and use
      # specified file
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # do not map nodemodules
      - /app/node_modules
      # map curr dir to /app
      - ./client:/app
  # this test service does not require port mapping
  # it does require file mapping in order for us to see changes in the test files
  # this tests service is another container for just running tests
  tests:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
      # this container needs to run different commands than the docker dev file on start
    command: ["npm", "run", "test"]
